#!/usr/local/sbin/charm-env python3

import os
import subprocess

from charms.layer.kubernetes_common import (
    get_node_name,
    kubectl,
)

from charmhelpers.core.hookenv import (
    action_fail,
    status_set,
)

# make sure the kubectl snap can be found
os.environ['PATH'] += os.pathsep + os.path.join(os.sep, 'snap', 'bin')

try:
    kubectl('uncordon', get_node_name())
except subprocess.CalledProcessError as e:
    action_fail('{}. See unit logs for details.'.format(str(e)))
    raise

status_set('active', 'Kubernetes unit resumed')
